// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('cocacola', async function() {
    // Test name: cocacola
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 857x691 |  | 
    await driver.manage().window().setRect({ width: 857, height: 691 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .form-control |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .form-control")).click()
    // 4 | click | css=.ng-scope:nth-child(1) > td .form-control |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .form-control")).click()
    // 5 | click | css=.ng-scope:nth-child(1) > td .form-control |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .form-control")).click()
    // 6 | click | css=.ng-scope:nth-child(1) > td .form-control |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .form-control")).click()
    // 7 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 8 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 9 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 10 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('allorders', async function() {
    // Test name: allorders
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 739x808 |  | 
    await driver.manage().window().setRect({ width: 739, height: 808 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 5 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 6 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 7 | click | id=ageInput |  | 
    await driver.findElement(By.id("ageInput")).click()
    // 8 | type | id=ageInput | 21 | 
    await driver.findElement(By.id("ageInput")).sendKeys("21")
    // 9 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('cancelorder', async function() {
    // Test name: cancelorder
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 739x808 |  | 
    await driver.manage().window().setRect({ width: 739, height: 808 })
    // 3 | click | css=.ng-scope:nth-child(1) > td > .row |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td > .row")).click()
    // 4 | mouseOver | css=.ng-scope:nth-child(1) > td .input-group-prepend > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-prepend > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 6 | click | css=.btn-default |  | 
    await driver.findElement(By.css(".btn-default")).click()
  })
  it('onebeer', async function() {
    // Test name: onebeer
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 739x808 |  | 
    await driver.manage().window().setRect({ width: 739, height: 808 })
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | id=ageInput |  | 
    await driver.findElement(By.id("ageInput")).click()
    // 6 | type | id=ageInput | 11 | 
    await driver.findElement(By.id("ageInput")).sendKeys("11")
    // 7 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 8 | click | id=ageInput |  | 
    await driver.findElement(By.id("ageInput")).click()
    // 9 | type | id=ageInput | 21 | 
    await driver.findElement(By.id("ageInput")).sendKeys("21")
    // 10 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('onewine', async function() {
    // Test name: onewine
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 739x808 |  | 
    await driver.manage().window().setRect({ width: 739, height: 808 })
    // 3 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | id=ageInput |  | 
    await driver.findElement(By.id("ageInput")).click()
    // 6 | type | id=ageInput | 18 | 
    await driver.findElement(By.id("ageInput")).sendKeys("18")
    // 7 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 8 | mouseOver | css=.btn-success |  | 
    {
      const element = await driver.findElement(By.css(".btn-success"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 9 | mouseOut | css=.btn-success |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 10 | mouseDownAt | id=ageInput | 1.5,14.2166748046875 | 
    {
      const element = await driver.findElement(By.id("ageInput"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 11 | mouseMoveAt | id=ageInput | 1.5,14.2166748046875 | 
    {
      const element = await driver.findElement(By.id("ageInput"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | mouseUpAt | id=ageInput | 1.5,14.2166748046875 | 
    {
      const element = await driver.findElement(By.id("ageInput"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 13 | click | id=ageInput |  | 
    await driver.findElement(By.id("ageInput")).click()
    // 14 | type | id=ageInput | 21 | 
    await driver.findElement(By.id("ageInput")).sendKeys("21")
    // 15 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('tomuchorders', async function() {
    // Test name: tomuchorders
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 739x808 |  | 
    await driver.manage().window().setRect({ width: 739, height: 808 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 5 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 6 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 7 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 8 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 9 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 10 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 11 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 12 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 13 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 14 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 15 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 16 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 17 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 18 | doubleClick | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 19 | doubleClick | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 20 | doubleClick | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 21 | doubleClick | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 22 | doubleClick | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 23 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 24 | doubleClick | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 25 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 26 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 27 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 28 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 29 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 30 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 31 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 32 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 33 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 34 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 35 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 36 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 37 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 38 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 39 | doubleClick | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 40 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 41 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 42 | doubleClick | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 43 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 44 | doubleClick | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |  | 
    {
      const element = await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 45 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
    // 46 | click | id=ageInput |  | 
    await driver.findElement(By.id("ageInput")).click()
    // 47 | type | id=ageInput | 56 | 
    await driver.findElement(By.id("ageInput")).sendKeys("56")
    // 48 | click | css=.btn-success |  | 
    await driver.findElement(By.css(".btn-success")).click()
  })
})
